---

# pandas_07_df 값변경

In [1]:
import numpy as np
import pandas as pd

In [2]:
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)

In [3]:
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [4]:
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [5]:
iphone_df.loc['iPhone 8', '메모리'] = '2.5GB'

In [6]:
iphone_df.loc['iPhone 8', '메모리']

'2.5GB'

In [7]:
iphone_df.loc['iPhone 8']

출시일        2017-09-22
디스플레이             4.7
메모리             2.5GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

In [8]:
iphone_df.loc['iPhone 8'] = ['2016-09-22', '4.7', '2GB', 'iOS 11.0', 'No']

In [9]:
iphone_df.loc['iPhone 8']

출시일        2016-09-22
디스플레이             4.7
메모리               2GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

In [10]:
iphone_df.loc[:, 'Face ID']

iPhone 7          No
iPhone 7 Plus     No
iPhone 8          No
iPhone 8 Plus     No
iPhone X         Yes
iPhone XS        Yes
iPhone XS Max    Yes
Name: Face ID, dtype: object

In [11]:
iphone_df.loc[:, 'Face ID'] = 'YES'

In [12]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0     YES
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0     YES
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0     YES
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0     YES
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     YES
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     YES
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     YES

In [21]:
iphone_df[['디스플레이', 'Face ID']]

              디스플레이 Face ID
iPhone 7        4.7     YES
iPhone 7 Plus   5.5     YES
iPhone 8        4.7     YES
iPhone 8 Plus   5.5     YES
iPhone X        5.8     YES
iPhone XS       5.8     YES
iPhone XS Max   6.5     YES

In [27]:
iphone_df['디스플레이'] == 5.5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X         False
iPhone XS        False
iPhone XS Max    False
Name: 디스플레이, dtype: bool

In [29]:
print(iphone_df.dtypes)

출시일        object
디스플레이      object
메모리        object
출시 버전      object
Face ID    object
dtype: object

In [30]:
iphone_df.loc[iphone_df['디스플레이'] == 5.5] = 'z'

In [32]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0     YES
iPhone 7 Plus           z     z    z         z       z
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0     YES
iPhone 8 Plus           z     z    z         z       z
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     YES
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     YES
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     YES

In [33]:
iphone_df[['디스플레이', 'Face ID']] = 'x'

In [34]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     x  2GB  iOS 10.0       x
iPhone 7 Plus           z     x    z         z       x
iPhone 8       2016-09-22     x  2GB  iOS 11.0       x
iPhone 8 Plus           z     x    z         z       x
iPhone X       2017-11-03     x  3GB  iOS 11.1       x
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [35]:
iphone_df.loc[['iPhone 7', 'iPhone X']]

                 출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7  2016-09-16     x  2GB  iOS 10.0       x
iPhone X  2017-11-03     x  3GB  iOS 11.1       x

In [36]:
iphone_df.loc[['iPhone 7', 'iPhone X']] = 'o'

In [37]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                o     o    o         o       o
iPhone 7 Plus           z     x    z         z       x
iPhone 8       2016-09-22     x  2GB  iOS 11.0       x
iPhone 8 Plus           z     x    z         z       x
iPhone X                o     o    o         o       o
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [38]:
iphone_df.loc['iPhone 7' : 'iPhone X']

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                o     o    o         o       o
iPhone 7 Plus           z     x    z         z       x
iPhone 8       2016-09-22     x  2GB  iOS 11.0       x
iPhone 8 Plus           z     x    z         z       x
iPhone X                o     o    o         o       o

In [51]:
iphone_df.loc['iPhone 7' : 'iPhone X'] = 'o'  # loc는 데이터 프레임 행열 명대로 사용

In [52]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                o     o    o         o       o
iPhone 7 Plus           o     o    o         o       o
iPhone 8                o     o    o         o       o
iPhone 8 Plus           o     o    o         o       o
iPhone X                o     o    o         o       o
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [53]:
iphone_df.iloc[[1, 3], [1, 4]]  # iloc는 꼭 숫자 좌표로 해야함

              디스플레이 Face ID
iPhone 7 Plus     o       o
iPhone 8 Plus     o       o

In [54]:
iphone_df.iloc[[1, 3], [1, 4]] = 'v'

In [59]:
iphone_df.loc['HJ phone'] = ['2021-09-24', 9.0, '256GB', 'iOS 99.0', 'YES']
iphone_df

                      출시일 디스플레이    메모리     출시 버전 Face ID
iPhone 7                o     o      o         o       o
iPhone 7 Plus           o     v      o         o       v
iPhone 8                o     o      o         o       o
iPhone 8 Plus           o     v      o         o       v
iPhone X                o     o      o         o       o
iPhone XS      2018-09-21     x    4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x    4GB  iOS 12.0       x
HJ phone       2021-09-24     9  256GB  iOS 99.0     YES

In [61]:
iphone_df['제조사'] = 'Apple'
iphone_df

                      출시일 디스플레이    메모리     출시 버전 Face ID    제조사
iPhone 7                o     o      o         o       o  Apple
iPhone 7 Plus           o     v      o         o       v  Apple
iPhone 8                o     o      o         o       o  Apple
iPhone 8 Plus           o     v      o         o       v  Apple
iPhone X                o     o      o         o       o  Apple
iPhone XS      2018-09-21     x    4GB  iOS 12.0       x  Apple
iPhone XS Max  2018-09-21     x    4GB  iOS 12.0       x  Apple
HJ phone       2021-09-24     9  256GB  iOS 99.0     YES  Apple

In [62]:
iphone_df.drop('HJ phone', axis='index', inplace=False)
iphone_df

                      출시일 디스플레이    메모리     출시 버전 Face ID    제조사
iPhone 7                o     o      o         o       o  Apple
iPhone 7 Plus           o     v      o         o       v  Apple
iPhone 8                o     o      o         o       o  Apple
iPhone 8 Plus           o     v      o         o       v  Apple
iPhone X                o     o      o         o       o  Apple
iPhone XS      2018-09-21     x    4GB  iOS 12.0       x  Apple
iPhone XS Max  2018-09-21     x    4GB  iOS 12.0       x  Apple
HJ phone       2021-09-24     9  256GB  iOS 99.0     YES  Apple

In [63]:
iphone_df.drop('HJ phone', axis='index', inplace=True)
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7                o     o    o         o       o  Apple
iPhone 7 Plus           o     v    o         o       v  Apple
iPhone 8                o     o    o         o       o  Apple
iPhone 8 Plus           o     v    o         o       v  Apple
iPhone X                o     o    o         o       o  Apple
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x  Apple
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x  Apple

In [64]:
iphone_df.drop('제조사', axis='columns', inplace=True)
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                o     o    o         o       o
iPhone 7 Plus           o     v    o         o       v
iPhone 8                o     o    o         o       o
iPhone 8 Plus           o     v    o         o       v
iPhone X                o     o    o         o       o
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [65]:
iphone_df.drop(['iPhone 7', 'iPhone X', 'iPhone XS Max'], axis='index', inplace=True)
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus           o     v    o         o       v
iPhone 8                o     o    o         o       o
iPhone 8 Plus           o     v    o         o       v
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x